version: "3.8"
services:
  db:
    image: postgres:12-alpine
    cap_add:
      - SYS_NICE
    restart: always
    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tenda
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres
volumes:
  db:
    driver: local


# docker-compose up -d